version: '3.9'

services:
  # seq:
  #   image: datalust/seq:latest
  #   container_name: "seq"
  #   volumes:
  #     - ~/apps/seq/data:/data
  #   ports:
  #     - '5341:80'
  #   environment:
  #     - ACCEPT_EULA=Y

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: "mssql-db"
    ports:
      - 5432:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AdminStashspace321